### 게시글 목록
GET http://localhost:8080/api/admin/boards/notice/posts

### 게시글 등록
POST http://localhost:8080/api/admin/boards/notice/posts
Content-Type: application/json

{
  "title"    : "공지사항 테스트",
  "content"  : "내용입니다.",
  "is_notice": 1,
  "is_use"   : 1
}